apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pyrom-prod

resources:
  - namespace.yaml
  - ../../base

commonLabels:
  environment: prod

patchesStrategicMerge:
  - pyrom-configmap.yaml

images:
  - name: bubthegreat/pyrom
    newTag: latest

