apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pyrom-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: pyrom.bubtaylor.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pyrom-service
                port:
                  number: 1337

