apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  # Production - port 1337
  "1337": "pyrom-prod/pyrom-service:1337"
  # Staging - port 1338
  "1338": "pyrom-staging/pyrom-service:1337"
  # Dev - port 1339
  "1339": "pyrom-dev/pyrom-service:1337"

